spring:
  application:
    name: Day07

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
          username: root
          password: 793273
        slave:
          url: jdbc:mysql://localhost:3306/dds_practice?serverTimezone=GMT%2B8
          username: root
          password: 793273

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


