spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
    username: root
    password: 793273
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl